In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('spam.csv')
print(df.info(),'\n',df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None
        Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Message'],df['spam'],test_size=0.2)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7676 sparse matrix of type '<class 'numpy.int64'>'
	with 59369 stored elements in Compressed Sparse Row format>

In [20]:
X_train_cv.shape

(4457, 7676)

In [22]:
v.get_feature_names_out()[1000:1050]

array(['anymore', 'anyone', 'anyones', 'anyplaces', 'anythin', 'anything',
       'anythingtomorrow', 'anytime', 'anyway', 'anyways', 'anywhere',
       'apart', 'apartment', 'apes', 'apeshit', 'apnt', 'apo',
       'apologetic', 'apologize', 'apology', 'app', 'apparently',
       'appeal', 'appendix', 'applausestore', 'applebees', 'application',
       'apply', 'applyed', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'appropriate', 'approved', 'apps',
       'appt', 'appy', 'april', 'aproach', 'apt', 'aptitude', 'aquarius',
       'ar', 'arab', 'arabian', 'arcade', 'archive', 'ard'], dtype=object)

In [28]:
print(v.get_feature_names_out()[6867])
v.vocabulary_

to

{'pls': 5243,
 'confirm': 1952,
 'the': 6745,
 'time': 6835,
 'to': 6867,
 'collect': 1884,
 'cheque': 1761,
 'then': 6758,
 'wait': 7282,
 'me': 4397,
 'at': 1115,
 'bus': 1566,
 'stop': 6436,
 'aft': 852,
 'ur': 7130,
 'lect': 4058,
 'lar': 4010,
 'if': 3595,
 'dun': 2479,
 'go': 3154,
 'get': 3114,
 'my': 4655,
 'car': 1643,
 'come': 1899,
 'back': 1191,
 'pick': 5186,
 'how': 3514,
 'much': 4622,
 'gave': 3085,
 'you': 7638,
 'morning': 4578,
 'ok': 4904,
 'change': 1717,
 'also': 926,
 'don': 2396,
 'know': 3953,
 'jack': 3774,
 'shit': 6055,
 'about': 758,
 'anything': 1005,
 'or': 4963,
 'say': 5891,
 'ask': 1094,
 'something': 6255,
 'helpful': 3394,
 'but': 1573,
 'want': 7307,
 'can': 1625,
 'pretend': 5369,
 'that': 6742,
 'did': 2296,
 'and': 962,
 'just': 3867,
 'text': 6720,
 'whatever': 7399,
 'in': 3637,
 'response': 5711,
 'hypotheticalhuagauahahuagahyuhagga': 3567,
 'nite': 4777,
 'pocay': 5262,
 'wocay': 7495,
 'luv': 4259,
 'more': 4574,
 'than': 6732,
 'thing': 6775,
 '4eva': 514,
 'promise': 5420,
 'ring': 5751,
 '2morrowxxxx': 398,
 'tell': 6690,
 'them': 6754,
 'drug': 2458,
 'dealer': 2183,
 'getting': 3121,
 'impatient': 3623,
 'we': 7340,
 'tried': 6972,
 'contact': 1974,
 're': 5556,
 'your': 7642,
 'reply': 5684,
 'our': 4995,
 'offer': 4888,
 'of': 4883,
 'video': 7208,
 'phone': 5173,
 '750': 614,
 'anytime': 1007,
 'any': 997,
 'network': 4742,
 'mins': 4485,
 'half': 3296,
 'price': 5377,
 'line': 4117,
 'rental': 5671,
 'camcorder': 1619,
 'call': 1601,
 '08000930705': 51,
 'hello': 3388,
 'good': 3178,
 'week': 7361,
 'fancy': 2773,
 'drink': 2442,
 'later': 4022,
 'todays': 6874,
 'voda': 7243,
 'numbers': 4847,
 'ending': 2580,
 '7548': 615,
 'are': 1050,
 'selected': 5958,
 'receive': 5591,
 '350': 443,
 'award': 1166,
 'have': 3348,
 'match': 4367,
 'please': 5235,
 '08712300220': 96,
 'quoting': 5506,
 'claim': 1811,
 'code': 1871,
 '4041': 476,
 'standard': 6383,
 'rates': 5542,
 'app': 1020,
 'so': 6233,
 'gonna': 3176,
 'deus': 2276,
 'ex': 2685,
 'great': 3231,
 'what': 7398,
 'attracts': 1133,
 'brothas': 1520,
 'awesome': 1169,
 'plan': 5219,
 'here': 3404,
 'after': 853,
 'like': 4104,
 'lt': 4242,
 'gt': 3250,
 'll': 4154,
 'details': 2272,
 'wee': 7359,
 'bit': 1369,
 'comedy': 1900,
 'cant': 1636,
 'laughing': 4028,
 'da': 2136,
 'ma': 4281,
 'fan': 2771,
 'yar': 7601,
 'wanted': 7309,
 'scold': 5907,
 'yest': 7622,
 'late': 4019,
 'already': 923,
 'where': 7407,
 'got': 3192,
 'zhong': 7667,
 'se': 5927,
 'qing': 5486,
 'b4': 1177,
 'he': 3358,
 'out': 4997,
 'all': 911,
 'lor': 4199,
 'still': 6424,
 'act': 797,
 'real': 5568,
 'sure': 6564,
 'mean': 4400,
 'made': 4294,
 'hold': 3459,
 'weed': 7360,
 'now': 4834,
 'step': 6413,
 'outta': 5010,
 'way': 7337,
 'congrats': 1958,
 'again': 858,
 'true': 6985,
 'dear': 2186,
 'sat': 5875,
 'pray': 5344,
 'evening': 2657,
 'felt': 2814,
 'sms': 6213,
 'some': 6246,
 'guaranteed': 3253,
 'latest': 4023,
 'nokia': 4793,
 '40gb': 479,
 'ipod': 3730,
 'mp3': 4600,
 'player': 5229,
 '500': 535,
 'prize': 5392,
 'txt': 7029,
 'word': 7514,
 'no': 4783,
 '83355': 663,
 'ibhltd': 3571,
 'ldnw15h': 4044,
 '150p': 306,
 'mtmsgrcvd18': 4619,
 'chance': 1715,
 'there': 6763,
 'search': 5929,
 'hard': 3328,
 'will': 7442,
 'it': 3753,
 'let': 4077,
 'try': 6992,
 'valentines': 7169,
 'day': 2174,
 'special': 6309,
 'win': 7444,
 'over': 5012,
 '1000': 256,
 'quiz': 5502,
 'take': 6626,
 'partner': 5079,
 'on': 4923,
 'trip': 6973,
 'lifetime': 4095,
 'send': 5970,
 '83600': 667,
 'msg': 4606,
 'rcvd': 5553,
 'custcare': 2119,
 '08718720201': 136,
 'hai': 3289,
 'priya': 5391,
 'right': 5746,
 'doctor': 2370,
 'said': 5842,
 'pa': 5031,
 'oh': 4899,
 'yes': 7621,
 've': 7188,
 'been': 1293,
 'little': 4145,
 'under': 7074,
 'weather': 7348,
 'kind': 3934,
 'coccooning': 1866,
 'home': 3467,
 'sch': 5902,
 'finish': 2859,
 'ard': 1049,
 'free': 2981,
 'entry': 2611,
 'into': 3710,
 '250': 366,
 'weekly': 7365,
 'comp': 1912,
 'enter': 2601,
 '84128': 671,
 '18': 321,
 'www': 7566,
 'textcomp': 6724,
 'com': 1893,
 'cust': 2118,
 'care': 1647,
 '08712405020': 106,
 'secret': 5936,
 'admirer': 822,
 'who': 7419,
 'is': 3742,
 'looking': 4191,
 'make': 4315,
 'with': 7471,
 'find': 2854,
 'they': 6771,
 'reveal': 5730,
 'thinks': 6781,
 '09058094594': 177,
 'hanks': 3316,
 'lotsly': 4210,
 'email': 2566,
 'do': 2364,
 'mind': 4473,
 'times': 6836,
 'per': 5132,
 'night': 4767,
 'lookatme': 4188,
 'thanks': 6736,
 'for': 2935,
 'purchase': 5467,
 'clip': 1835,
 'from': 3018,
 'charged': 1726,
 '35p': 445,
 'think': 6777,
 'better': 1332,
 'why': 7427,
 'not': 4819,
 'mmsto': 4523,
 '32323': 439,
 'same': 5857,
 'eerie': 2532,
 'tones': 6896,
 '4u': 529,
 'rply': 5799,
 'tone': 6895,
 'title': 6850,
 '8007': 637,
 'eg': 2538,
 'dracula': 2428,
 'titles': 6851,
 'ghost': 3124,
 'addamsfa': 810,
 'munsters': 4636,
 'exorcist': 2706,
 'twilight': 7023,
 'getzed': 3122,
 'co': 1862,
 'uk': 7053,
 'pobox36504w45wq': 5257,
 'up': 7113,
 'own': 5024,
 'oga': 4898,
 'left': 4061,
 'saw': 5890,
 'messages': 4446,
 'hope': 3483,
 'weekend': 7363,
 'ya': 7594,
 'tel': 6686,
 'wats': 7334,
 'problem': 5399,
 'afternoon': 855,
 'sunshine': 6548,
 'dawns': 2173,
 'refreshed': 5624,
 'happy': 3327,
 'be': 1270,
 'alive': 910,
 'breathe': 1493,
 'air': 884,
 'smile': 6203,
 'love': 4221,
 'as': 1086,
 'always': 931,
 'woke': 7496,
 'yeesh': 7612,
 'its': 3760,
 'didn': 2297,
 'fall': 2762,
 'asleep': 1101,
 'til': 6832,
 'am': 933,
 'one': 4927,
 'issues': 3752,
 'california': 1600,
 'okay': 4905,
 'snow': 6228,
 'manageable': 4326,
 'finished': 2861,
 'missing': 4500,
 'plenty': 5240,
 'hey': 3414,
 'rite': 5761,
 'put': 5477,
 '10': 254,
 'evey': 2673,
 'mnth': 4525,
 'jay': 3793,
 'says': 5894,
 'double': 2412,
 'faggot': 2748,
 'wan': 7302,
 'watch': 7326,
 'infernal': 3664,
 'affair': 844,
 'mila': 4463,
 'age23': 863,
 'blonde': 1398,
 'new': 4749,
 'look': 4187,
 'sex': 6004,
 'guys': 3275,
 'fun': 3040,
 'mtalk': 4615,
 '69866': 591,
 '30pp': 430,
 '1st': 333,
 '5free': 552,
 '50': 534,
 'increments': 3652,
 'help08718728876': 3393,
 'well': 7378,
 'boy': 1469,
 'glad': 3143,
 'wasted': 7323,
 'applebees': 1025,
 'nothing': 4824,
 'bad': 1194,
 'girl': 3133,
 'remember': 5653,
 'private': 5390,
 '2003': 345,
 'account': 785,
 'statement': 6397,
 '07808': 35,
 'xxxxxx': 7588,
 'shows': 6088,
 '800': 634,
 'un': 7062,
 'redeemed': 5613,
 'points': 5270,
 '08719899217': 154,
 'identifier': 3589,
 '41685': 481,
 'expires': 2718,
 '07': 19,
 '11': 268,
 '04': 14,
 'im': 3611,
 'inperialmusic': 3679,
 'listening2the': 4140,
 'weirdest': 7372,
 'track': 6939,
 'ever': 2661,
 'by': 1585,
 'leafcutter': 4049,
 'john': 3831,
 'sounds': 6289,
 'insects': 3682,
 'being': 1311,
 'molested': 4551,
 'someone': 6250,
 'plumbing': 5244,
 'remixed': 5662,
 'evil': 2674,
 'men': 4433,
 'acid': 791,
 'babe': 1184,
 'enough': 2599,
 'money': 4559,
 'bread': 1486,
 'milk': 4466,
 'give': 3139,
 'when': 7403,
 'cool': 2001,
 'ish': 3745,
 'anymore': 1000,
 'else': 2562,
 'having': 3354,
 'too': 6906,
 'without': 7475,
 'see': 5945,
 'tomorrow': 6893,
 'jess': 3811,
 'ttyl': 7003,
 'hi': 3417,
 'address': 815,
 'has': 3337,
 'changed': 1718,
 'wenever': 7383,
 'lik': 4103,
 'vikky': 7217,
 'darlin': 2159,
 'helens': 3385,
 'fone': 2926,
 'princes': 5381,
 'tb': 6663,
 'kate': 3893,
 'going': 3166,
 'theatre': 6749,
 'wherever': 7409,
 'drive': 2447,
 'forced': 2937,
 'myself': 4660,
 'eat': 2509,
 'slice': 6178,
 'really': 5576,
 'hungry': 3548,
 'tho': 6791,
 'this': 6786,
 'sucks': 6517,
 'mark': 4349,
 'worried': 7525,
 'knows': 3956,
 'sick': 6104,
 'turn': 7012,
 'down': 2419,
 'pizza': 5213,
 'lol': 4177,
 'willing': 7443,
 'pay': 5105,
 'aight': 881,
 'close': 1839,
 'around': 1072,
 'alex': 902,
 'place': 5215,
 'haf': 3286,
 'combine': 1898,
 'everything': 2670,
 'need': 4721,
 'actually': 806,
 'could': 2025,
 'yourself': 7646,
 'yor': 7636,
 'work': 7516,
 'man': 4324,
 'rent': 5670,
 'even': 2656,
 'fill': 2841,
 'fucking': 3031,
 'gas': 3080,
 'tank': 6643,
 'stressed': 6458,
 'depressed': 2252,
 'thanksgiving': 6738,
 'cuz': 2131,
 'reason': 5579,
 'team': 6674,
 'budget': 1542,
 'available': 1151,
 'last': 4017,
 'buy': 1577,
 'unsold': 7105,
 'players': 5230,
 'base': 1234,
 'rate': 5541,
 'bath': 1245,
 'ill': 3607,
 'key': 3913,
 'window': 7447,
 'ned': 4720,
 'convince': 1994,
 'him': 3427,
 'tht': 6813,
 'possible': 5305,
 'witot': 7477,
 'hurting': 3556,
 'his': 3434,
 'feeling': 2807,
 'main': 4312,
 'best': 1327,
 'orange': 4967,
 'tariffs': 6647,
 'camera': 1621,
 'phones': 5176,
 'mobileupd8': 4535,
 '08000839402': 50,
 '2stoptxt': 410,
 'cs': 2086,
 'booked': 1427,
 'pilates': 5199,
 'yoga': 7634,
 'lesson': 4075,
 'haha': 3287,
 'thanx': 6740,
 'brownie': 1524,
 'nice': 4760,
 'working': 7520,
 'room': 5781,
 'very': 7201,
 'soon': 6271,
 'hadn': 3285,
 'clocks': 1837,
 'shouted': 6080,
 'everyone': 2667,
 'realised': 5571,
 'was': 7318,
 'wahay': 7277,
 'another': 983,
 'hour': 3507,
 'bed': 1286,
 'newest': 4751,
 'harry': 3336,
 'potter': 5315,
 'order': 4971,
 'phoenix': 5172,
 'book': 1426,
 'answer': 986,
 'questions': 5495,
 'first': 2872,
 'among': 947,
 'readers': 5564,
 'sorry': 6278,
 'yeah': 7609,
 'gudnite': 3257,
 'tc': 6665,
 'practice': 5332,
 'she': 6035,
 'coming': 1904,
 'pattern': 5100,
 'emerging': 2572,
 'friends': 3004,
 'telling': 6691,
 'smoke': 6208,
 'fiend': 2827,
 'impede': 3624,
 'their': 6751,
 'doing': 2386,
 'other': 4988,
 'things': 6776,
 'hesitant': 3410,
 'aiyar': 889,
 'type': 7040,
 'sony': 6268,
 'ericsson': 2624,
 'salesman': 5848,
 'shuhui': 6096,
 'quite': 5500,
 'gd': 3094,
 'use': 7146,
 'considering': 1969,
 '86888': 683,
 'reward': 5736,
 'hours': 3509,
 'talk': 6633,
 'subscribe6gbp': 6504,
 'inc': 3639,
 '3hrs': 457,
 '16': 317,
 'txtstop': 7038,
 'gamb': 3065,
 'tv': 7017,
 'forwarded': 2961,
 '448712404000': 496,
 '08712404000': 105,
 'immediately': 3620,
 'an': 957,
 'urgent': 7134,
 'message': 4444,
 'waiting': 7285,
 'reach': 5557,
 'only': 4933,
 'dont': 2400,
 'gent': 3104,
 'trying': 6994,
 'weekends': 7364,
 'draw': 2433,
 'won': 7500,
 '09064012160': 210,
 'k52': 3872,
 'valid': 7170,
 '12hrs': 288,
 '150ppm': 310,
 'should': 6077,
 'stay': 6401,
 'hear': 3368,
 'treated': 6967,
 'urself': 7141,
 'digi': 2313,
 'cam': 1618,
 'off': 4885,
 '9pm': 737,
 'fab': 2740,
 'year': 7610,
 'coupla': 2031,
 'wks': 7487,
 '7250i': 610,
 'auction': 1135,
 'part': 5074,
 '86021': 680,
 'hg': 3416,
 'suite342': 6531,
 '2lands': 392,
 'row': 5794,
 'w1jhl': 7266,
 '2marrow': 393,
 'wed': 7353,
 'aha': 872,
 'hero': 3405,
 'leaving': 4057,
 'qatar': 5483,
 'tonite': 6903,
 'apt': 1041,
 'opportunity': 4954,
 'keep': 3902,
 'touch': 6929,
 'kerala': 3909,
 'joined': 3833,
 'today': 6873,
 'itself': 3761,
 'battery': 1248,
 'died': 2301,
 '645': 577,
 'house': 3510,
 'maid': 4307,
 'murderer': 4640,
 'coz': 2042,
 'murdered': 4639,
 'th': 6731,
 'january': 3788,
 'public': 5454,
 'holiday': 3463,
 'govt': 3201,
 'instituitions': 3693,
 'closed': 1841,
 'including': 3646,
 'post': 5307,
 'office': 4891,
 'understand': 7076,
 'wewa': 7397,
 '130': 291,
 'iriver': 3734,
 '255': 368,
 '128': 286,
 'mb': 4391,
 'kiss': 3941,
 'miss': 4497,
 'baby': 1187,
 'beautiful': 1277,
 'truth': 6991,
 'against': 859,
 'gravity': 3226,
 'read': 5563,
 'carefully': 1653,
 'heart': 3372,
 'feels': 2809,
 'light': 4100,
 'heavy': 3377,
 'leaves': 4056,
 'press': 5367,
 'conference': 1949,
 'loads': 4159,
 'during': 2485,
 'nasty': 4689,
 'cough': 2023,
 'dry': 2465,
 'shot': 6075,
 'help': 3390,
 'services': 5992,
 'inclusive': 3647,
 'credits': 2065,
 'goto': 3196,
 'comuk': 1937,
 'net': 4737,
 'login': 4172,
 '3qxj9': 465,
 'unsubscribe': 7108,
 'extra': 2731,
 'charge': 1725,
 '08702840625': 79,
 '220': 356,
 'cm2': 1855,
 '9ae': 734,
 'colours': 1892,
 'colour': 1891,
 'darker': 2157,
 'done': 2398,
 'styling': 6493,
 'hair': 3291,
 'ringtone': 5753,
 'reference': 5617,
 'number': 4846,
 'x49': 7570,
 'mobile': 4531,
 'arrive': 1078,
 'customer': 2121,
 '09065989182': 222,
 'placement': 5217,
 'ah': 871,
 'xy': 7592,
 'lunch': 4254,
 'opinion': 4952,
 'abt': 766,
 'character': 1723,
 'lucky': 4249,
 'told': 6884,
 'earlier': 2496,
 'pple': 5325,
 'ft': 3027,
 'combination': 1897,
 'str': 6449,
 'smth': 6217,
 '09064017295': 212,
 'pm': 5249,
 'smoking': 6211,
 'while': 7414,
 'people': 5131,
 'wylie': 7567,
 'smokes': 6210,
 'justify': 3869,
 'ruining': 5813,
 'leave': 4055,
 'wif': 7434,
 'carry': 1663,
 'meh': 4421,
 'num': 4845,
 '98321561': 731,
 'familiar': 2768,
 'dudette': 2475,
 'god': 3159,
 'asked': 1096,
 'forgiveness': 2946,
 'child': 1775,
 'lovely': 4224,
 'wonderful': 7503,
 'fruit': 3024,
 'tree': 6971,
 'gives': 3141,
 'hurt': 3555,
 'stone': 6433,
 'write': 7545,
 'dictionary': 2295,
 'mode': 4542,
 'cover': 2039,
 'screen': 5922,
 'hand': 3304,
 'gently': 3107,
 'remove': 5664,
 'interesting': 3702,
 'used': 7147,
 'driving': 2450,
 'usf': 7152,
 'lot': 4207,
 'stoners': 6434,
 'ahead': 873,
 'petey': 5162,
 'whereare': 7408,
 'friendsare': 3005,
 'thekingshead': 6753,
 'canlove': 1632,
 'nic': 4759,
 'gr8prizes': 3207,
 'wkly': 7485,
 '8800': 694,
 'psp': 5446,
 'cash': 1668,
 'every': 2662,
 'wk': 7481,
 '80878': 647,
 'http': 3530,
 '08715705022': 125,
 'plz': 5248,
 'sir': 6135,
 'aiyo': 890,
 'her': 3403,
 'early': 2498,
 'sleepin': 6171,
 'okie': 4908,
 'liao': 4084,
 'den': 2237,
 'huh': 3540,
 'fast': 2782,
 'dat': 2165,
 'means': 4404,
 'havent': 3351,
 'painting': 5044,
 'hmmm': 3449,
 'guess': 3259,
 'kb': 3899,
 'power': 5321,
 'dunno': 2481,
 'tahan': 6622,
 'anot': 982,
 'thk': 6787,
 'lo': 4158,
 'oso': 4986,
 'forgot': 2947,
 'coughing': 2024,
 'life': 4092,
 'strict': 6463,
 'teacher': 6671,
 'bcoz': 1264,
 'teaches': 6672,
 'amp': 950,
 'conducts': 1947,
 'exam': 2688,
 'lessons': 4076,
 'stubborn': 6475,
 'hospital': 3498,
 'kept': 3908,
 'weak': 7341,
 'sucker': 6515,
 'hospitals': 3499,
 'suckers': 6516,
 'nt': 4839,
 'many': 4340,
 'reasons': 5581,
 'called': 1608,
 'bbd': 1254,
 'thts': 6814,
 'chikku': 1774,
 'hw': 3564,
 'dvg': 2489,
 'cold': 1880,
 'heard': 3369,
 'vinobanagar': 7222,
 'violence': 7224,
 'condition': 1945,
 'ru': 5807,
 'darren': 2162,
 'saying': 5893,
 'meeting': 4417,
 'ge': 3095,
 'meet': 4415,
 'dinner': 2324,
 'cos': 2015,
 'feel': 2805,
 'awkward': 1170,
 'wnevr': 7492,
 'wana': 7304,
 'fal': 2760,
 'vth': 7259,
 'books': 1430,
 'fals': 2766,
 'yen': 7617,
 'madodu': 4295,
 'nav': 4703,
 'pretsorginta': 5370,
 'nammanna': 4680,
 'pretsovru': 5371,
 'important': 3626,
 'alwa': 930,
 'gud': 3255,
 'eveb': 2655,
 'thank': 6735,
 'boooo': 1432,
 'quit': 5499,
 'registered': 5634,
 'vote': 7251,
 'uploaded': 7124,
 'mine': 4476,
 'facebook': 2743,
 'drop': 2453,
 'years': 7611,
 'eve': 2654,
 'went': 7384,
 'party': 5082,
 'boyfriend': 1471,
 'si': 6100,
 'saturday': 5883,
 'cherish': 1762,
 'brother': 1521,
 'role': 5775,
 'model': 4543,
 'waliking': 7289,
 'slow': 6188,
 'wat': 7325,
 'cleaning': 1826,
 'baaaaabe': 1183,
 'misss': 4503,
 'youuuuu': 7647,
 'teach': 6670,
 'class': 1819,
 'alone': 921,
 'bored': 1437,
 'accept': 776,
 'begging': 1303,
 '08712402779': 103,
 'fine': 2856,
 'bitch': 1370,
 'goodmorning': 3181,
 'grandfather': 3216,
 'expired': 2717,
 'bluff': 1409,
 'leh': 4065,
 'sleep': 6170,
 'makes': 4316,
 'dearer': 2188,
 'de': 2180,
 'happiness': 3326,
 'pain': 5041,
 'dem': 2235,
 'arnt': 1071,
 'pissed': 5208,
 'id': 3584,
 'would': 7537,
 'xxxxxxxxxxxxxx': 7591,
 'intrepid': 3711,
 'duo': 2482,
 'both': 1444,
 'senthil': 5982,
 'group': 3245,
 'company': 1914,
 'apnt': 1015,
 '5pm': 558,
 'informed': 3668,
 'unable': 7063,
 'cal': 1595,
 'lets': 4078,
 'bhaskar': 1341,
 'deep': 2207,
 'show': 6083,
 'euro': 2649,
 '2004': 346,
 'england': 2590,
 'flag': 2884,
 '3lions': 458,
 'click': 1832,
 'following': 2925,
 'service': 5991,
 'info': 3665,
 'had': 3284,
 'foot': 2932,
 'before': 1299,
 'bought': 1449,
 'ron': 5780,
 'present': 5362,
 'swatch': 6583,
 'wrong': 7553,
 'join': 3832,
 ...}

In [35]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [37]:
X_test_cv = v.transform(X_test)
y_pred = model.predict(X_test_cv)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix

rpt = classification_report(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print(cm,'\n\n',rpt)

[[963   1]
 [ 18 133]]

               precision    recall  f1-score   support

           0       0.98      1.00      0.99       964
           1       0.99      0.88      0.93       151

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [42]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectoriser',CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train,y_train)

Pipeline(steps=[('vectoriser', CountVectorizer()), ('nb', MultinomialNB())])

In [43]:
clf.score(X_test,y_test)

0.9829596412556054

In [54]:
i = 2
print("Message",df['Message'][i])
print("Prediction",'spam' if clf.predict([df['Message'][i]]).item() == 1 else 'ham')

Message Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
Prediction spam

### Exercise

In [1]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv('movies_sentiment_data.csv')
print(df.info(),'\n\n',df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19000 entries, 0 to 18999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     19000 non-null  object
 1   sentiment  19000 non-null  object
dtypes: object(2)
memory usage: 297.0+ KB
None

                                                    review sentiment
count                                               19000     19000
unique                                              18939         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    4      9500

In [6]:
print(df.shape, df.head())

(19000, 2)                                               review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [7]:
df['Category'] = df['sentiment'].apply(lambda x : 1 if x == 'positive' else 0)
df.head()

                                              review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [8]:
df['Category'].value_counts()

Category
1    9500
0    9500
Name: count, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df['review'],df['sentiment'],test_size=0.2)

In [17]:
pipeline = Pipeline([
    ('vectoriser',CountVectorizer()),
    ('rf',RandomForestClassifier(n_estimators=50, criterion='entropy'))
])

pipeline.fit(X_train,y_train)

Pipeline(steps=[('vectoriser', CountVectorizer()),
                ('rf',
                 RandomForestClassifier(criterion='entropy', n_estimators=50))])

In [18]:
y_pred = pipeline.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

    negative       0.82      0.83      0.83      1902
    positive       0.83      0.82      0.82      1898

    accuracy                           0.82      3800
   macro avg       0.83      0.82      0.82      3800
weighted avg       0.83      0.82      0.82      3800

In [19]:
pipeline_2 = Pipeline([
    ('vectoriser',CountVectorizer()),
    ('knn',KNeighborsClassifier(n_neighbors=10, metric='euclidean'))
])

pipeline_3 = Pipeline([
    ('vectoriser',CountVectorizer()),
    ('nb',MultinomialNB())
])

pipeline_2.fit(X_train,y_train)
pipeline_3.fit(X_train,y_train)

y_pred2 = pipeline_2.predict(X_test)
y_pred3 = pipeline_3.predict(X_test)

print("Classification Report for KNN", classification_report(y_test,y_pred2))
print("Classification Report for NB", classification_report(y_test,y_pred3))

Classification Report for KNN               precision    recall  f1-score   support

    negative       0.65      0.63      0.64      1902
    positive       0.64      0.66      0.65      1898

    accuracy                           0.65      3800
   macro avg       0.65      0.65      0.65      3800
weighted avg       0.65      0.65      0.65      3800

Classification Report for NB               precision    recall  f1-score   support

    negative       0.83      0.86      0.85      1902
    positive       0.86      0.82      0.84      1898

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800